quantiles:
  - "0.5"
  - "0.8"
  - "0.95"
  - "0.99"
tmp_directory: "/tmp/metricreplicator"
prometheus:
  host: "http://localhost:9090"
groups:
  - description: "Network size grows with fixed latency"
#    network:
#      - name: "latency"
#        value: "50ms"
    ranges:
      - start_time: 1589292280
        interval: "3m"
        props:
          - name: "network_size"
            value: "17"
webdav:
  timeout: "1m"
commit_hash: "fake500"
